### PR TITLE
Add support for detecting "0x<hex>" colors

### PR DESCRIPTION
**Pull request by khughitt**
Small change to allow colorizer to operate on colors of the form "0xAABBCC".

### CODE REVIEW

**Comment by khughitt** [comment]
Added some more changes after realizing that the initial commit only dealt with detection.

It's still not working for "\0", but I'm guessing this should be pretty close...

Any ideas? This is my first real attempt at doing anything useful with vimscript :smile:

**Comment by noscript** [comment]
Please merge!

**Comment by lilydjwg** [comment]
Unfortunately this doesn't work as expected. It throws errors while I'm typing `0x123456`.

**Comment by khughitt** [comment]
@lilydjwg Apologies! The PR is unfinished.. It seemed like it should be close though, so I thought I would submit the PR for feedback..

Any ideas what might be missing?..

**Comment by lilydjwg** [comment]
You may want to check [vim-hexokinase](https://github.com/RRethy/vim-hexokinase) which supports this (and has much more features).

**Pull request closed without merging**
